### ISSUE TITLE
Some suggestions for features

### ISSUE THREAD

**Issue by akumpf** [bradleyg/nserv#3]
This is a great project.  Just some suggestions of things that could make it immediately useful to the community of Node devs wanting to start their own Platform-as-a-Service (PaaS) setup.
- add to NPM for easy install (I see this one is already on your list)
- add command to restart an app (the forever '-w' command to watch for changes may be enough here, but I'm not sure); perhaps `./nserv restart (domain)`
- by default, the GIT repo probably wants to just be a subdirectory within the app (since git creates the ".git" subdirectory by default, most projects are setup that way) 
- some more details in the help page about how to changes routes while nserv is running (it looks like you have most of those hooks in place by having the main service watch for changes to the config file, but spelling that out would be helpful for anyone wanting to quickly get it up and running).
- basic stats could also be great for debugging/admin (things like how long a domain has been up and running, mem usage, number of connections, etc). `./nserv stats (domain)`

Again, I think this is a great much-needed project and has a lot of potential.  I've forked it and will experiment a bit, but I think you have a better handle on it and wanted to add my 2 cents. :)

Cheers,
Adam

**Comment by bradleyg** [comment]
Great to hear some feedback, thanks. Have been thinking about some your requests, and implemented some of them.  
- now on npm  
- git repo is now ".git"  

One thing I'm not sure I understand is the "restart app" request. Being able to restart an app _should_ be an option but how does 'forever -w' help here? Every time an app update is pushed via git there is a post-receive hook that updates and restarts the app already. Are you are editing the files directly on the server? i could understand this request if so...  

Stats are a great idea and I'll start work on that, I'll try and get a better description of how the system works up too.  

Cheers!

**Comment by akumpf** [comment]
Yeah, I had been looking at the '-w' option in the forever process for doing local file changes. The post-receive hook is great for remote updates; is there a simple way of triggering that when working locally?

It's looking awesome, and I'm excited to see this project moving along so quickly! Thanks. :)
